#cloud-config
timezone: Europe/Berlin
package_update: true
package_upgrade: true
packages:
  %{~ if enable_terraria ~}
  - unzip
  %{~ endif ~}
  %{~ if enable_valheim ~}
  - lib32gcc1
  %{~ endif ~}
  %{~ if enable_minecraft ~}
  - openjdk-17-jdk
  %{~ endif ~}
mounts:
  - [${mount_device}, /mnt/${mount_name}, ${mount_format}, "discard,nofail,defaults", "0", "0"]

write_files:
  - path: /mnt/${mount_name}/terraria_serverconfig.txt
    owner: root:root
    permissions: 0666
    defer: true
    content: |
      world=/mnt/${mount_name}/terraria/worlds/${terraria_world_name}.wld
      worldpath=/mnt/${mount_name}/terraria/worlds/
      autocreate=${terraria_world_size}
      worldname=${terraria_world_name}
      difficulty=${terraria_difficulty}
      port=${terraria_port}
      password=${terraria_password}
      worldrollbackstokeep=1
      secure=1
      language=${terraria_language}
      upnp=1

  - path: /mnt/${mount_name}/adminlist.txt
    owner: root:root
    permissions: 0666
    defer: true
    content: |
      ${admin_id}
  
  - path: /mnt/${mount_name}/valheim_start_server.sh
    owner: root:root
    permissions: 0666
    defer: true
    content: |
      #!/bin/bash
      export templdpath=$LD_LIBRARY_PATH
      export LD_LIBRARY_PATH=/root/valheim/linux64:$LD_LIBRARY_PATH
      export SteamAppId=892970

      echo "Starting server PRESS CTRL-C to exit"

      /root/valheim/valheim_server.x86_64 -name ${valheim_server_name} -port ${valheim_port} -world ${valheim_world_name} -password ${valheim_password} -nographics -batchmode -public ${valheim_public} -savedir "/mnt/${mount_name}/valheim" &

      export LD_LIBRARY_PATH=$templdpath

  - path: /mnt/${mount_name}/server.properties
    owner: root:root
    permissions: 0777
    defer: true
    content: |
      allow_flight=${minecraft_allow_flight}
      allow_nether=${minecraft_allow_nether}
      broadcast-console-to-ops=${minecraft_broadcast-console-to-ops}
      broadcast-rcon-to-ops=${minecraft_broadcast-rcon-to-ops}
      difficulty=${minecraft_difficulty}
      enable-command-block=${minecraft_enable-command-block}
      enable-jmx-monitoring=${minecraft_enable-jmx-monitoring}
      enable-rcon=${minecraft_enable-rcon}
      enable-status=${minecraft_enable-status}
      enable-query=${minecraft_enable-query}
      enforce-secure-profile=${minecraft_enforce-secure-profile}
      enforce-whitelist=${minecraft_enforce-whitelist}
      entity-broadcast-range-percentage=${minecraft_entity-broadcast-range-percentage}
      force-gamemode=${minecraft_force-gamemode}
      function-permission-level=${minecraft_function-permission-level}
      gamemode=${minecraft_gamemode}
      generate-structures=${minecraft_generate-structures}
      generator-settings=${minecraft_generator-settings}
      hardcore=${minecraft_hardcore}
      hide-online-players=${minecraft_hide-online-players}
      initial-disabled-packs=${minecraft_initial-disabled-packs}
      initial-enabled-packs=${minecraft_initial-enabled-packs}
      level-name=/mnt/${mount_name}/${minecraft_level-name}
      level-seed=${minecraft_level-seed}
      level-type=${minecraft_level-type}
      max-chained-neighbor-updates=${minecraft_max-chained-neighbor-updates}
      max-players=${minecraft_max-players}
      max-tick-time=${minecraft_max-tick-time}
      max-world-size=${minecraft_max-world-size}
      motd=${minecraft_motd}
      network-compression-threshold=${minecraft_network-compression-threshold}
      online-mode=${minecraft_online-mode}
      op-permission-level=${minecraft_op-permission-level}
      player-idle-timeout=${minecraft_player-idle-timeout}
      prevent-proxy-connections=${minecraft_prevent-proxy-connections}
      previews-chat=${minecraft_previews-chat}
      pvp=${minecraft_pvp}
      query-port=${minecraft_query-port}
      rate-limit=${minecraft_rate-limit}
      rcon-password=${minecraft_rcon-password}
      rcon-port=${minecraft_rcon-port}
      resource-pack=${minecraft_resource-pack}
      resource-pack-prompt=${minecraft_resource-pack-prompt}
      resource-pack-sha1=${minecraft_resource-pack-sha1}
      require-resource-pack=${minecraft_require-resource-pack}
      server-ip=${minecraft_server-ip} 
      server-port=${minecraft_server-port}
      simulation-distance=${minecraft_simulation-distance}
      snooper_enabled=${minecraft_snooper_enabled}
      spawn-animals=${minecraft_spawn-animals}
      spawn-monsters=${minecraft_spawn-monsters}
      spawn-npcs=${minecraft_spawn-npcs}
      spawn-protection=${minecraft_spawn-protection}
      sync-chunk-writes=${minecraft_sync-chunk-writes}
      use-native-transport=${minecraft_use-native-transport}
      view-distance=${minecraft_view-distance}
      white-list=${minecraft_white-list}

runcmd:
  # Firewall Rules to connect with ssh
  - ufw --force enable
  - ufw allow 22/tcp

  # add terraria to vm 
  %{~ if enable_terraria ~}
  - ufw allow ${terraria_port}/tcp
  - wget https://terraria.org/api/download/pc-dedicated-server/terraria-server-${terraria_version}.zip -P /root/terraria/
  - unzip /root/terraria/terraria-server* -d /root/terraria
  - chmod +x /root/terraria/${terraria_version}/Linux/TerrariaServer.bin.x86*
  - tmux new-session -d -s terraria /root/terraria/${terraria_version}/Linux/TerrariaServer.bin.x86_64 -config /mnt/${mount_name}/terraria_serverconfig.txt -ip ${ip_address}
  %{~ endif ~}

  # add valheim to vm
  %{~ if enable_valheim ~}
  - ufw allow 2456/udp && ufw allow 2457/udp && ufw allow 2458/udp && ufw allow 27060/udp
  - wget "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" -P /root
  - tar zxvf /root/steamcmd_linux.tar.gz -C /root
  - /root/steamcmd.sh +@sSteamCmdForcePlatformType linux +force_install_dir /root/valheim +login anonymous +app_update 896660 validate +quit
  - mv /mnt/${mount_name}/adminlist.txt /mnt/${mount_name}/valheim/adminlist.txt
  - tmux new-session -d -s valheim
  - tmux send-keys -t valheim /mnt/${mount_name}/valheim_start_server.sh C-m
  %{~ endif ~}

  # add minecraft to vm
  %{~ if enable_minecraft ~}
  - ufw allow 25565/tcp
  - mkdir /root/minecraft
  - wget "https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.2.0/forge-1.19.2-43.2.0-installer.jar" -P /root/minecraft
  - cd /root/minecraft
  - mv forge-1.19.2-43.2.0-installer.jar server.jar
  - java -jar server.jar --installServer
  - ./run.sh nogui
  %{~ for mod in minecraft_mods ~}
  - wget ${mod} -P /root/minecraft/mods/
  %{~ endfor ~}
  - echo -e "\n-Xms${minecraft_ram}G" >> user_jvm_args.txt
  - echo -e "\n-Xmx${minecraft_ram}G" >> user_jvm_args.txt
  - sed -i 's/eula=false/eula=true/g' eula.txt
  - cp /mnt/${mount_name}/server.properties .
  - tmux new-session -d -s minecraft ./run.sh nogui
  %{~ endif ~}